name: gen_stuff
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - conda-forge::pydantic
  - conda-forge::spacy
  - pytest
  - scikit-learn
  - conda-forge::sentence-transformers
  - conda-forge::python-levenshtein
  - conda-forge::ebooklib